name: asan
on: [push, pull_request]
jobs:
  asan:
    name: asan
    runs-on: ubuntu-22.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - name: deps
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: humble
      - name: install_clang
        run: sudo apt update && sudo apt install -y clang clang-tools lld
      - name: build_and_test
        uses: ros-tooling/action-ros-ci@v0.2
        env:
          CC: clang
          CXX: clang++
          # orensbruli: new_delete_type_mismatch=0 added because a problem Probably related to some problem in rcl or rclcpp in humble. Check from time to time.
          ASAN_OPTIONS: 'detect_leaks=0:new_delete_type_mismatch=0'
        with:
          target-ros2-distro: humble
          # build all packages listed in the meta package
          package-name: |
            rmf_traffic_ros2
            rmf_task_ros2
            rmf_fleet_adapter
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/open-rmf/rmf/main/rmf.repos
          colcon-defaults: |
            {
              "build": {
                "mixin": ["asan-gcc", "lld"],
                "cmake-args": ["-DCMAKE_BUILD_TYPE=Debug"],
                "executor": "sequential"
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - name: upload_test_stream
        uses: actions/upload-artifact@v2
        with:
          name: colcon-test-logs
          path: ${{ steps.build_and_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_traffic/streams.log
        if: always()
