name: github pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
    - name: download-deps
      run: |
        sudo apt update
        sudo apt install -y wget
        wget https://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
        sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
        sudo apt update && sudo apt install \
          git cmake python3-pydocstyle curl libyaml-cpp-dev -y
    - name: workspace
      run: |
        mkdir -p rmf_ws/src
        cd rmf_ws/src
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: rmf_ws/src/
    - name: gen_docs
      shell: bash
      run: |
        cd rmf_ws/src/rmf_fleet_adapter_python/docs
        ls
        bash gen_docs.sh
    - name: deploy_page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: rmf_ws/src/rmf_fleet_adapter_python/docs/
